# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: RyanOnMars.TermKey
PackageVersion: 0.2.6
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: termkey.exe
    PortableCommandAlias: termkey
Scope: user
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ryanonmars/TermKey/releases/download/v0.2.6/termkey-windows-x86_64.zip
    InstallerSha256: 879e573c0a50e4643e74658126afdba4cb1eeeaa78f2ff2d9db28c9ba1ddeaa6
ManifestType: installer
ManifestVersion: 1.6.0
